; PlatformIO Project Configuration File
; ==============================================================
[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ============================================================
; 🌟 核心救命修复：强制使用 DIO 模式读写 Flash，专治合宙无限重启！
; ============================================================
board_build.flash_mode = dio

; 扩大分区表，防止大程序超出 Flash 容量
board_build.partitions = huge_app.csv

; 🛡️ 终极防护 1：开启深度依赖扫描，逼迫编译器深入每个文件
lib_ldf_mode = deep+

; 🛡️ 终极防护 2：强行屏蔽掉自带的 WebServer 库，杜绝冲突
lib_ignore = WebServer

; 编译参数
build_flags = 
    -I include
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1  ; 如果烧录后看不到串口日志，把这里的 1 改成 0 即可

; 依赖库配置
lib_deps = 
    ; 手动点名系统底层依赖
    WiFi
    FS
    Update
    ; 使用 ESPHome 官方维护的增强版
    esphome/AsyncTCP-esphome @ ^2.1.1
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2
    bblanchon/ArduinoJson @ ^6.21.0